import type { WarRoomData } from "./types";

export const mockWarRoomData: WarRoomData = {
  source: "mock",
  sourceLabel: "Mock local",
  updatedAt: new Date().toISOString(),
  globalOverview: {
    investment: 1_920_000,
    revenue: 5_580_000,
    utmifySyncAt: "Agora mesmo",
  },
  squads: {
    facebook: {
      name: "Squad Facebook",
      focus: "FB Ads + UGC",
      creativeVelocity: 17,
      creativeVelocityTarget: 14,
      validatedCreatives: 11,
      managerComment:
        "CPM estabilizou, mas 3 criativos perderam tracao no dia 2. Prioridade: novas aberturas nos primeiros 5 segundos.",
    },
    googleYoutube: {
      name: "Squad Google/YouTube",
      focus: "Search + VVC + Display",
      creativeVelocity: 9,
      creativeVelocityTarget: 12,
      validatedCreatives: 5,
      managerComment:
        "Search performando com CAC baixo. Gargalo na camada de VVC com baixo hold rate apos 15s.",
    },
  },
  liveAdsTracking: [
    {
      id: "FB-101",
      squad: "facebook",
      campaign: "Scale UGC CBO",
      adName: "Dor aguda + prova social",
      impressions: 182_440,
      views3s: 63_671,
      views15s: 21_200,
      ic: 3_102,
      lp: 9_741,
      roas: 2.7,
    },
    {
      id: "FB-118",
      squad: "facebook",
      campaign: "Retargeting D7",
      adName: "Quebra de objecao de preco",
      impressions: 96_200,
      views3s: 25_012,
      views15s: 4_430,
      ic: 890,
      lp: 3_460,
      roas: 1.9,
    },
    {
      id: "YT-034",
      squad: "googleYoutube",
      campaign: "YouTube VVC Broad",
      adName: "Comparativo visual 45s",
      impressions: 130_900,
      views3s: 32_070,
      views15s: 5_904,
      ic: 1_204,
      lp: 6_020,
      roas: 2.1,
    },
    {
      id: "GG-211",
      squad: "googleYoutube",
      campaign: "Search High Intent",
      adName: "Headline DR direcional",
      impressions: 74_330,
      views3s: 26_313,
      views15s: 13_945,
      ic: 1_833,
      lp: 5_892,
      roas: 3.2,
    },
  ],
  creativeFactory: {
    tasks: [
      {
        id: "TASK-001",
        squad: "facebook",
        title: "V3 - Hook anti-erro de escalada",
        owner: "Copy Ana",
        status: "Roteiro",
        metricContext: "Hold < 20% em FB-118",
        updatedAt: "09:40",
      },
      {
        id: "TASK-002",
        squad: "facebook",
        title: "UGC autoridade com prova visual",
        owner: "Creator Leo",
        status: "Gravacao",
        metricContext: "Hook em queda nas ultimas 24h",
        updatedAt: "10:15",
      },
      {
        id: "TASK-003",
        squad: "googleYoutube",
        title: "Cut 30s para VVC broad",
        owner: "Editor Nati",
        status: "Edicao",
        metricContext: "Retencao baixa apos 15s",
        updatedAt: "10:33",
      },
      {
        id: "TASK-004",
        squad: "googleYoutube",
        title: "Search variant CTA final",
        owner: "Copy Bruno",
        status: "Teste",
        metricContext: "Escalar CTR sem subir CPC",
        updatedAt: "11:02",
      },
      {
        id: "TASK-005",
        squad: "facebook",
        title: "Winner UGC depoimento selfie",
        owner: "Squad FB",
        status: "Winner",
        metricContext: "ROAS > 2.5 em 48h",
        updatedAt: "11:29",
      },
    ],
  },
  dailyBriefing: [
    {
      id: "BRIEF-1",
      squad: "facebook",
      trafficManagerComment:
        "Criativo FB-118 caiu para Hold 17,7%. Preciso de V2 com transicao de prova antes dos 12s e CTA aberto.",
      replies: [
        {
          role: "Copy",
          author: "Ana",
          version: "V2",
          assetUrl: "https://drive.google.com/file/d/brief-fb-v2",
          note: "Abri com pergunta direta e antecipei mecanismo no segundo 8.",
        },
        {
          role: "Edicao",
          author: "Nati",
          version: "V3",
          assetUrl: "https://drive.google.com/file/d/brief-fb-v3",
          note: "Nova trilha, corte mais rapido e CTA final em tela cheia.",
        },
      ],
    },
    {
      id: "BRIEF-2",
      squad: "googleYoutube",
      trafficManagerComment:
        "VVC com Hook 24,5%. Preciso teste de mini-historia com prova visual ate 15s para destravar retencao.",
      replies: [
        {
          role: "Copy",
          author: "Bruno",
          version: "V2",
          assetUrl: "https://drive.google.com/file/d/brief-yt-v2",
          note: "Roteiro com ponte narrativa e promessa mais explicita no inicio.",
        },
      ],
    },
  ],
  finance: {
    netRevenue: 2_120_000,
    profitMargin: 38.0,
    approvalRate: 87.2,
    ltv: 1_930,
  },
  activityLog: [
    {
      id: "LOG-001",
      actorRole: "Media Buyer",
      actorName: "Gestor Caio",
      action: "pausou criativo",
      entity: "FB-118",
      reason: "baixo Hook Rate",
      timestamp: "11:42",
    },
    {
      id: "LOG-002",
      actorRole: "Copywriter",
      actorName: "Ana",
      action: "subiu versao",
      entity: "V4 - Dor aguda + prova",
      reason: "iteracao para elevar Hold Rate",
      timestamp: "11:48",
    },
    {
      id: "LOG-003",
      actorRole: "Editor",
      actorName: "Nati",
      action: "publicou corte",
      entity: "YT-034 V3",
      reason: "feedback de retencao do gestor",
      timestamp: "11:53",
    },
  ],
};
