import type { WarRoomData } from "./types";

export const mockWarRoomData: WarRoomData = {
  source: "mock",
  sourceLabel: "Mock local",
  updatedAt: new Date().toISOString(),
  globalOverview: {
    investment: 1_920_000,
    revenue: 5_580_000,
    utmifySyncAt: "Agora mesmo",
    trafficSources: [
      { source: "Facebook Ads", spend: 980_000 },
      { source: "Google/YouTube", spend: 620_000 },
      { source: "TikTok Ads", spend: 210_000 },
      { source: "Native + Afiliados", spend: 110_000 },
    ],
  },
  squads: {
    facebook: {
      name: "Squad Facebook",
      focus: "FB Ads + UGC",
      creativeVelocity: 17,
      creativeVelocityTarget: 14,
      validatedCreatives: 11,
      managerComment:
        "CPM estabilizou, mas 3 criativos perderam tracao no dia 2. Prioridade: novas aberturas nos primeiros 5 segundos.",
    },
    googleYoutube: {
      name: "Squad Google/YouTube",
      focus: "Search + VVC + Display",
      creativeVelocity: 9,
      creativeVelocityTarget: 12,
      validatedCreatives: 5,
      managerComment:
        "Search performando com CAC baixo. Gargalo na camada de VVC com baixo hold rate apos 15s.",
    },
    tiktok: {
      name: "Squad TikTok",
      focus: "UGC velocity + Spark Ads",
      creativeVelocity: 14,
      creativeVelocityTarget: 16,
      validatedCreatives: 7,
      managerComment: "Squad com bom volume, mas com sinais iniciais de fadiga por frequencia em criativos campeoes.",
    },
  },
  liveAdsTracking: [
    {
      id: "FB-101",
      squad: "facebook",
      campaign: "Scale UGC CBO",
      adName: "Dor aguda + prova social",
      impressions: 182_440,
      clicks: 13_830,
      views3s: 63_671,
      views15s: 21_200,
      ic: 3_102,
      lp: 9_741,
      roas: 2.7,
      frequency: 2.6,
      uniqueCtr: 2.9,
      aov: 347,
      upsellConversion: 18.4,
      ltv: 1_980,
      cpa: 124,
      trend24h: {
        hookRate: [30.8, 31.2, 31.6, 32.1, 31.8, 31.4, 31.0, 31.8],
        holdRate: [33.5, 34.2, 34.9, 34.5, 34.1, 33.8, 33.4, 33.3],
        roas: [2.3, 2.4, 2.5, 2.7, 2.8, 2.8, 2.7, 2.7],
      },
      frequencyTrend3d: [2.2, 2.4, 2.6],
      uniqueCtrTrend3d: [3.1, 3.0, 2.9],
    },
    {
      id: "FB-118",
      squad: "facebook",
      campaign: "Retargeting D7",
      adName: "Quebra de objecao de preco",
      impressions: 96_200,
      clicks: 5_940,
      views3s: 25_012,
      views15s: 4_430,
      ic: 890,
      lp: 3_460,
      roas: 1.9,
      frequency: 3.9,
      uniqueCtr: 1.1,
      aov: 286,
      upsellConversion: 9.2,
      ltv: 1_280,
      cpa: 192,
      trend24h: {
        hookRate: [21.5, 20.8, 19.9, 19.5, 18.9, 18.5, 18.2, 17.9],
        holdRate: [23.1, 22.4, 21.2, 20.4, 19.5, 18.7, 18.0, 17.7],
        roas: [2.2, 2.1, 2.0, 2.0, 1.9, 1.9, 1.9, 1.9],
      },
      frequencyTrend3d: [3.2, 3.5, 3.9],
      uniqueCtrTrend3d: [1.5, 1.3, 1.1],
    },
    {
      id: "YT-034",
      squad: "googleYoutube",
      campaign: "YouTube VVC Broad",
      adName: "Comparativo visual 45s",
      impressions: 130_900,
      clicks: 8_550,
      views3s: 32_070,
      views15s: 5_904,
      ic: 1_204,
      lp: 6_020,
      roas: 2.1,
      frequency: 2.1,
      uniqueCtr: 1.8,
      aov: 318,
      upsellConversion: 14.9,
      ltv: 1_720,
      cpa: 161,
      trend24h: {
        hookRate: [25.3, 25.8, 25.0, 24.9, 24.7, 24.6, 24.5, 24.5],
        holdRate: [20.9, 20.4, 19.8, 19.6, 19.4, 19.2, 18.9, 18.4],
        roas: [2.3, 2.2, 2.2, 2.2, 2.1, 2.1, 2.1, 2.1],
      },
      frequencyTrend3d: [1.8, 1.9, 2.1],
      uniqueCtrTrend3d: [2.1, 1.9, 1.8],
    },
    {
      id: "GG-211",
      squad: "googleYoutube",
      campaign: "Search High Intent",
      adName: "Headline DR direcional",
      impressions: 74_330,
      clicks: 7_210,
      views3s: 26_313,
      views15s: 13_945,
      ic: 1_833,
      lp: 5_892,
      roas: 3.2,
      frequency: 1.7,
      uniqueCtr: 3.7,
      aov: 401,
      upsellConversion: 22.3,
      ltv: 2_360,
      cpa: 138,
      trend24h: {
        hookRate: [33.2, 34.0, 34.5, 35.0, 35.4, 35.1, 35.0, 35.4],
        holdRate: [49.5, 50.4, 51.0, 51.9, 52.5, 52.1, 51.8, 53.0],
        roas: [2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.1, 3.2],
      },
      frequencyTrend3d: [1.5, 1.6, 1.7],
      uniqueCtrTrend3d: [3.9, 3.8, 3.7],
    },
    {
      id: "TT-077",
      squad: "tiktok",
      campaign: "Spark Scale 25-44",
      adName: "POV transformacao em 18s",
      impressions: 214_110,
      clicks: 12_820,
      views3s: 69_900,
      views15s: 16_420,
      ic: 1_940,
      lp: 8_880,
      roas: 2.4,
      frequency: 3.8,
      uniqueCtr: 1.2,
      aov: 336,
      upsellConversion: 16.1,
      ltv: 1_860,
      cpa: 172,
      trend24h: {
        hookRate: [34.2, 33.7, 33.1, 32.9, 32.7, 32.3, 32.0, 31.6],
        holdRate: [26.2, 25.8, 25.2, 24.8, 24.2, 23.7, 23.1, 22.6],
        roas: [2.8, 2.7, 2.7, 2.6, 2.6, 2.5, 2.5, 2.4],
      },
      frequencyTrend3d: [3.0, 3.4, 3.8],
      uniqueCtrTrend3d: [1.8, 1.5, 1.2],
    },
  ],
  creativeFactory: {
    tasks: [
      {
        id: "TASK-001",
        squad: "facebook",
        title: "V3 - Hook anti-erro de escalada",
        owner: "Copy Ana",
        status: "Roteiro",
        metricContext: "Hold < 20% em FB-118",
        updatedAt: "09:40",
      },
      {
        id: "TASK-002",
        squad: "facebook",
        title: "UGC autoridade com prova visual",
        owner: "Creator Leo",
        status: "Gravacao",
        metricContext: "Hook em queda nas ultimas 24h",
        updatedAt: "10:15",
      },
      {
        id: "TASK-003",
        squad: "googleYoutube",
        title: "Cut 30s para VVC broad",
        owner: "Editor Nati",
        status: "Edicao",
        metricContext: "Retencao baixa apos 15s",
        updatedAt: "10:33",
      },
      {
        id: "TASK-004",
        squad: "googleYoutube",
        title: "Search variant CTA final",
        owner: "Copy Bruno",
        status: "Teste",
        metricContext: "Escalar CTR sem subir CPC",
        updatedAt: "11:02",
      },
      {
        id: "TASK-005",
        squad: "facebook",
        title: "Winner UGC depoimento selfie",
        owner: "Squad FB",
        status: "Winner",
        metricContext: "ROAS > 2.5 em 48h",
        updatedAt: "11:29",
      },
      {
        id: "TASK-006",
        squad: "tiktok",
        title: "Pattern Interrupt para Spark V2",
        owner: "Editor Nati",
        status: "Teste",
        metricContext: "Fadiga detectada em TT-077",
        updatedAt: "11:38",
      },
    ],
  },
  dailyBriefing: [
    {
      id: "BRIEF-1",
      squad: "facebook",
      trafficManagerComment:
        "Criativo FB-118 caiu para Hold 17,7%. Preciso de V2 com transicao de prova antes dos 12s e CTA aberto.",
      replies: [
        {
          role: "Copy",
          author: "Ana",
          version: "V2",
          assetUrl: "https://drive.google.com/file/d/brief-fb-v2",
          note: "Abri com pergunta direta e antecipei mecanismo no segundo 8.",
        },
        {
          role: "Edicao",
          author: "Nati",
          version: "V3",
          assetUrl: "https://drive.google.com/file/d/brief-fb-v3",
          note: "Nova trilha, corte mais rapido e CTA final em tela cheia.",
        },
      ],
    },
    {
      id: "BRIEF-2",
      squad: "googleYoutube",
      trafficManagerComment:
        "VVC com Hook 24,5%. Preciso teste de mini-historia com prova visual ate 15s para destravar retencao.",
      replies: [
        {
          role: "Copy",
          author: "Bruno",
          version: "V2",
          assetUrl: "https://drive.google.com/file/d/brief-yt-v2",
          note: "Roteiro com ponte narrativa e promessa mais explicita no inicio.",
        },
      ],
    },
    {
      id: "BRIEF-3",
      squad: "tiktok",
      trafficManagerComment:
        "Criativo TT-077 com sinais de fadiga. Preciso V2 com pattern interrupt nos 2 primeiros segundos.",
      replies: [
        {
          role: "Edicao",
          author: "Nati",
          version: "V2",
          assetUrl: "https://drive.google.com/file/d/brief-tt-v2",
          note: "Inserido corte de surpresa no frame inicial para recuperar CTR unico.",
        },
      ],
    },
  ],
  commandCenter: {
    tasks: [
      {
        id: "DEM-001",
        department: "trafficMedia",
        title: "Criativo winner com fadiga",
        description: "FB-118 com queda de CTR e aumento de frequencia. Avaliar refresh imediato.",
        squadHead: "Head Midia - Caio",
        assignee: "Media Buyer A",
        status: "doing",
        impact: "critical",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
        lastMovedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        dueAt: new Date(Date.now() + 1000 * 60 * 60 * 5).toISOString(),
        dependencyIds: [],
        doneApproval: {
          required: false,
          approved: false,
          approvedBy: "",
          approvedRole: "",
          approvedAt: "",
          note: "",
        },
        decisionLog: [
          {
            at: "08:20",
            author: "Head Midia - Caio",
            note: "Demanda aberta apos alerta de fadiga no winner.",
          },
        ],
      },
      {
        id: "DEM-002",
        department: "copyResearch",
        title: "Refatorar lead da VSL",
        description: "Hold rate abaixo da meta no bloco inicial de 15s.",
        squadHead: "Head Copy - Ana",
        assignee: "Copywriter B",
        status: "backlog",
        impact: "high",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
        lastMovedAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
        dueAt: new Date(Date.now() + 1000 * 60 * 60 * 12).toISOString(),
        dependencyIds: ["DEM-001"],
        doneApproval: {
          required: false,
          approved: false,
          approvedBy: "",
          approvedRole: "",
          approvedAt: "",
          note: "",
        },
        decisionLog: [
          {
            at: "09:05",
            author: "Head Copy - Ana",
            note: "Aguardando contexto final de trafego para script.",
          },
        ],
      },
      {
        id: "DEM-003",
        department: "editorsCreative",
        title: "Novas variacoes de gancho V2/V3",
        description: "Criar 3 aberturas com pattern interrupt para criativo em escala.",
        squadHead: "Head Edicao - Nati",
        assignee: "Editor A",
        status: "review",
        impact: "critical",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
        lastMovedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        dueAt: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
        dependencyIds: ["DEM-001"],
        doneApproval: {
          required: true,
          approved: false,
          approvedBy: "",
          approvedRole: "",
          approvedAt: "",
          note: "",
        },
        decisionLog: [
          {
            at: "10:40",
            author: "Editor A",
            note: "Subida V2 com cortes a cada 3s para aprovacao do head.",
          },
        ],
      },
      {
        id: "DEM-004",
        department: "techCro",
        title: "Auditoria de checkout",
        description: "Abandono acima de 60% em Yampi. Revisar performance e friccao.",
        squadHead: "Head Tech - Bruno",
        assignee: "CRO Analyst",
        status: "backlog",
        impact: "critical",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 13).toISOString(),
        lastMovedAt: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
        dueAt: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
        dependencyIds: [],
        doneApproval: {
          required: false,
          approved: false,
          approvedBy: "",
          approvedRole: "",
          approvedAt: "",
          note: "",
        },
        decisionLog: [
          {
            at: "07:58",
            author: "Head Tech - Bruno",
            note: "Task critica aberta pelo gatilho de abandono de carrinho.",
          },
        ],
      },
    ],
    squadMembers: {
      copyResearch: ["Copywriter A", "Copywriter B", "Research Analyst"],
      trafficMedia: ["Media Buyer A", "Media Buyer B", "Ops Trafego"],
      editorsCreative: ["Editor A", "Editor B", "Motion Designer"],
      techCro: ["CRO Analyst", "Fullstack Dev", "QA Checkout"],
    },
  },
  finance: {
    netRevenue: 2_120_000,
    profitMargin: 38.0,
    contributionMargin: 31.5,
    approvalRate: 87.2,
    approvalCard: 84.3,
    approvalPix: 93.1,
    ltv24h: 512,
    upsellTakeRate: 21.4,
    ltv: 1_930,
  },
  squadSync: {
    lastReportAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    dailyInput: {
      creativeId: "FB-118",
      kpisToday: {
        hookRate: 18.7,
        holdRate15s: 27.3,
        ctrOutbound: 1.1,
        icRate: 10.8,
        frequency: 3.9,
      },
      kpisYesterday: {
        hookRate: 20.5,
        holdRate15s: 29.1,
        ctrOutbound: 1.4,
        icRate: 11.6,
        frequency: 3.4,
      },
      sentimentNotes:
        "Objeções recorrentes sobre prazo de entrega e percepção de preço. Comentários pedindo prova de resultado no primeiro bloco.",
    },
    commandOrders: [
      {
        id: "ORD-001",
        audience: "editors",
        status: "failing",
        title: "Novo Gancho para Winner em Saturacao",
        diagnosis: "ROAS > 2.0 com Hook abaixo de 20% em FB-118.",
        action: "Criar 3 variações de pattern interrupt para os 5s iniciais.",
        createdAt: "11:54",
      },
      {
        id: "ORD-002",
        audience: "techCro",
        status: "failing",
        title: "Friccao de Checkout",
        diagnosis: "IC Rate global abaixo de 12%.",
        action: "Revisar velocidade da LP + campos de checkout e gatilhos de confiança.",
        createdAt: "11:55",
      },
    ],
    notifications: {
      lastDispatchAt: "11:56",
      lastMessage: "Diagnóstico enviado para Edição e Tech/CRO.",
      slackStatus: "simulated",
      whatsappStatus: "simulated",
    },
  },
  integrations: {
    apiStatus: {
      utmify: {
        status: "online",
        lastSync: "11:58",
        trend12h: [2.6, 2.5, 2.7, 2.8, 2.6, 2.9, 3.0, 2.8, 2.9, 3.1, 3.0, 3.2],
        errorMessage: "",
      },
      appmax: {
        status: "online",
        lastSync: "11:57",
        trend12h: [86, 87, 88, 85, 84, 86, 87, 89, 88, 87, 86, 85],
        errorMessage: "",
      },
      kiwify: {
        status: "syncing",
        lastSync: "11:56",
        trend12h: [18, 18.2, 18.4, 18.1, 18.8, 19, 19.4, 19.1, 19.6, 19.8, 20.1, 20.3],
        errorMessage: "",
      },
      yampi: {
        status: "online",
        lastSync: "11:55",
        trend12h: [58, 57, 59, 60, 58, 57, 56, 55, 57, 58, 59, 58],
        errorMessage: "",
      },
    },
    attribution: {
      realRoiLeaderboard: [
        { creativeId: "GG-211", source: "google", realProfit: 319_000, realRoas: 3.52 },
        { creativeId: "FB-101", source: "meta", realProfit: 284_000, realRoas: 3.14 },
        { creativeId: "TT-077", source: "native", realProfit: 177_000, realRoas: 2.42 },
      ],
      namingDriftAlerts: [
        {
          creativeId: "FB-10I",
          severity: "warning",
          reason: "Possivel typo no ID de criativo importado (I vs 1).",
          suggestedRegistryId: "ID1450",
          suggestedDnaName: "LP9D_BRECHA_INSULINA_VSL_H04_ID1450",
        },
      ],
      validatedAssets: [
        {
          assetId: "1450",
          inputCpa: 98,
          effectiveCpa: 98,
          status: "scale",
          trackingSource: "facebookApi",
          note: "Escala vertical permitida.",
          salesVolumeShare: 24,
        },
        {
          assetId: "1400",
          inputCpa: 103,
          effectiveCpa: 103,
          status: "scale",
          trackingSource: "facebookApi",
          note: "Escala vertical permitida.",
          salesVolumeShare: 22,
        },
        {
          assetId: "1402",
          inputCpa: 95,
          effectiveCpa: 95,
          status: "scale",
          trackingSource: "facebookApi",
          note: "Escala vertical permitida.",
          salesVolumeShare: 20,
        },
        {
          assetId: "1059",
          inputCpa: 129,
          effectiveCpa: 129,
          status: "pause",
          trackingSource: "facebookApi",
          note: "Pausar e refatorar gancho.",
          salesVolumeShare: 18,
        },
        {
          assetId: "1076",
          inputCpa: 135,
          effectiveCpa: 135,
          status: "pause",
          trackingSource: "facebookApi",
          note: "Pausar e abrir tasks espelho.",
          salesVolumeShare: 16,
        },
        {
          assetId: "1400 REFEITO",
          inputCpa: 107,
          effectiveCpa: 107,
          status: "stabilize",
          trackingSource: "utmifyClickToPurchase",
          note: "Tracking error: ignorar API do Facebook e validar apenas Utmify C2P.",
          salesVolumeShare: 11,
        },
      ],
    },
    gateway: {
      consolidatedGrossRevenue: 5_640_000,
      consolidatedNetRevenue: 4_180_000,
      appmaxCardApprovalRate: 85.2,
      appmaxPreviousDayApprovalRate: 91.4,
      yampiCartAbandonmentRate: 58.1,
      fixedCosts: 320_000,
      taxRatePct: 8.5,
      kiwifyUpsellTakeRates: {
        upsell1: 27.4,
        upsell2: 16.9,
        upsell3: 8.7,
      },
    },
    merCross: {
      value: 2.94,
      totalSpend: 1_920_000,
      status: "stable",
      trend12h: [2.5, 2.6, 2.7, 2.6, 2.8, 2.7, 2.9, 3.0, 2.9, 3.1, 3.0, 2.94],
      recommendation: "MER acima de 2.5x. Manter controle de escala com monitoramento horario.",
    },
    fortress: {
      vault: {
        lastCheckAt: "12:00",
        intervalMinutes: 30,
        overallStatus: "warning",
        domains: [
          {
            domain: "checkout-principal.com",
            safeBrowsingStatus: "safe",
            facebookDebuggerStatus: "ok",
            cloudflareStatus: "up",
            blacklistHits: 0,
            status: "ok",
            note: "Dominio principal sem risco de blacklist no ultimo check.",
            checkedAt: "12:00",
          },
          {
            domain: "reserva-warroom.com",
            safeBrowsingStatus: "unknown",
            facebookDebuggerStatus: "warning",
            cloudflareStatus: "degraded",
            blacklistHits: 0,
            status: "warning",
            note: "Facebook Debugger com inconsistencias de scrape. Revisar DNS e OG tags.",
            checkedAt: "12:00",
          },
        ],
      },
      pixelSync: {
        realPurchases: 1230,
        metaReportedPurchases: 1018,
        discrepancyPct: 17.24,
        status: "healthy",
        lastCheckAt: "12:01",
        note: "Sincronia CAPI dentro da faixa operacional.",
      },
      backEndLtv: {
        upsellFlowMap: [
          { step: "Order Bump", takeRate: 26.4, estimatedRevenue: 196_000, status: "scale" },
          { step: "Upsell 1", takeRate: 27.4, estimatedRevenue: 422_000, status: "scale" },
          { step: "Upsell 2", takeRate: 16.9, estimatedRevenue: 247_000, status: "attention" },
          { step: "Upsell 3", takeRate: 8.7, estimatedRevenue: 96_000, status: "attention" },
        ],
        upsellTree: [
          {
            fromProduct: "Core Offer",
            toProduct: "Order Bump",
            buyersFrom: 1230,
            buyersTo: 325,
            attachRate: 26.4,
            benchmarkAttachRate: 20,
            status: "healthy",
          },
          {
            fromProduct: "Order Bump",
            toProduct: "Upsell 1",
            buyersFrom: 325,
            buyersTo: 89,
            attachRate: 27.4,
            benchmarkAttachRate: 20,
            status: "healthy",
          },
          {
            fromProduct: "Upsell 1",
            toProduct: "Upsell 2",
            buyersFrom: 89,
            buyersTo: 15,
            attachRate: 16.9,
            benchmarkAttachRate: 20,
            status: "warning",
          },
        ],
        attachRateAlerts: ["Attach Rate de Upsell 2 abaixo de 20%. Head Copy deve revisar argumentacao e prova de valor."],
        revenueBySource: {
          paidTraffic: 4_030_000,
          crmEmail: 310_000,
          crmSms: 142_000,
          crmWhatsapp: 198_000,
          crmTotal: 650_000,
          total: 4_680_000,
          crmSharePct: 13.89,
        },
        ltvTracker: {
          d7: 618,
          d30: 920,
          d90: 1_930,
        },
        predictiveModel: {
          predictedLtv90d: 2_040,
          baselineFromD7: 1_390,
          confidencePct: 78,
          drivers: ["Aprovacao Appmax estavel", "Take-rate de upsell acima de 15%", "Share CRM crescente"],
        },
        cohort90d: [
          { cohortLabel: "Mar/26", projectedRevenue: 1_140_000, source: "paid" },
          { cohortLabel: "Mar/26", projectedRevenue: 238_000, source: "crm" },
          { cohortLabel: "Fev/26", projectedRevenue: 1_020_000, source: "paid" },
          { cohortLabel: "Fev/26", projectedRevenue: 210_000, source: "crm" },
        ],
      },
      scaleSimulator: {
        defaultAdSpend: 1_920_000,
        defaultCpa: 148,
        projectedPurchases: 12_972,
        projectedNetProfit: 2_985_000,
        roiPct: 55.33,
      },
      executiveBriefing: {
        generatedAt: "18:00",
        summary:
          "Hoje o ID 1450 sustentou escala com MER em 2.94x, enquanto o fluxo de checkout manteve abandono controlado.",
        suggestedAction:
          "Aumentar budget apenas em ativos com CPA < 105 e priorizar correcao do dominio reserva-warroom.com no debugger.",
      },
      siren: {
        active: false,
        reasons: [],
        severity: "normal",
      },
    },
    operations: {
      opportunityLost: {
        estimatedLossToday: 4_200,
        currentLossPerMinute: 140,
        currentlyLosing: false,
        incidents: [
          {
            id: "INC-OPP-001",
            severity: "warning",
            reason: "Queda temporaria de aprovacao Appmax em janela de pico.",
            estimatedLoss: 4_200,
            startedAt: "10:12",
          },
        ],
      },
      reconciliation: {
        status: "warning",
        lastCheckedAt: "12:06",
        ledger: [
          {
            id: "spend_vs_utmify",
            expected: 1_920_000,
            observed: 1_905_000,
            variancePct: -0.78,
            status: "ok",
            note: "Diferenca dentro da tolerancia operacional.",
          },
          {
            id: "gross_vs_gateways",
            expected: 5_640_000,
            observed: 5_580_000,
            variancePct: -1.06,
            status: "warning",
            note: "Aguardando fechamento de lotes D0 em gateway.",
          },
        ],
      },
      worker: {
        queueDepth: 0,
        failedJobs: 0,
        processedToday: 47,
        lastRunAt: "12:06",
      },
      killSwitch: {
        active: false,
        merThreshold: 1.8,
        requiredDurationMinutes: 120,
        belowThresholdSince: "",
        triggeredAt: "",
        alertsSent: 0,
        autoTrafficBlocked: false,
        reason: "MER dentro da zona operacional.",
        peakWindow: "08:00-23:00",
      },
    },
  },
  contingency: {
    domains: [
      { name: "checkout-principal.com", status: "ok", score: 92, lastCheck: "12:03" },
      { name: "reserva-warroom.com", status: "warning", score: 68, lastCheck: "12:03" },
    ],
    adAccounts: [
      { name: "BM Escala Latam", status: "ok", score: 88, lastCheck: "12:02" },
      { name: "Google Ads Conta 02", status: "blocked", score: 34, lastCheck: "12:04" },
    ],
    fanpages: [
      { name: "Pagina Oficial DR", status: "ok", score: 90, lastCheck: "12:05" },
      { name: "Pagina Escala 02", status: "warning", score: 61, lastCheck: "12:05" },
    ],
  },
  enterprise: {
    ceoFinance: {
      grossRevenue: 5_580_000,
      adSpend: 1_920_000,
      gatewayFees: 201_000,
      nfseTaxes: 474_000,
      netProfit: 2_985_000,
      mer: 2.91,
      ltvCohorts: {
        d30: 920,
        d60: 1_480,
        d90: 1_930,
      },
      paybackDays: 17,
      taxProvision: 474_000,
      recoveryLeaderboard: [
        { agent: "Rafa CS", boletoRecoveryRate: 21.4, pixRecoveryRate: 36.8, recoveredRevenue: 148_000 },
        { agent: "Luana CS", boletoRecoveryRate: 19.9, pixRecoveryRate: 34.1, recoveredRevenue: 132_500 },
        { agent: "Marcos Recovery", boletoRecoveryRate: 17.8, pixRecoveryRate: 31.2, recoveredRevenue: 119_400 },
      ],
    },
    copyResearch: {
      uniqueMechanismProblem: "Saturacao criativa acelera CAC quando o avatar para de se reconhecer no angulo.",
      uniqueMechanismSolution: "Sistema de rotacao orientado por Pattern Interrupt + backlog de mecanismos testados por squad.",
      bigIdeaVault: [
        {
          id: "BIG-1",
          title: "Metodo anti-escalada cega",
          saturation: 42,
          expiresAt: "2026-05-20",
          uniqueMechanism: "Janela de substituicao de hook orientada por shelf-life e sinal de frequencia.",
          marketSophisticationLevel: 3,
          assetValue: 420_000,
        },
        {
          id: "BIG-2",
          title: "Framework de lucratividade por cohort",
          saturation: 65,
          expiresAt: "2026-04-12",
          uniqueMechanism: "Enriquecimento do lead por awareness e redistribuicao de oferta por LTV preditivo.",
          marketSophisticationLevel: 4,
          assetValue: 615_000,
        },
      ],
      avatarDossier: [
        {
          pain: "Escalar sem previsibilidade de lucro",
          desire: "ROAS estavel com caixa positivo",
          objection: "Ja testei varias copys sem resultado",
          supportInsight: "Ticket tende a subir quando oferta tem comparativo visual direto.",
        },
      ],
      namingRegistry: [
        {
          id: "DNA-1450",
          product: "LP9D",
          bigIdea: "BRECHA",
          mechanism: "INSULINA",
          format: "VSL",
          hookVariation: "H04",
          uniqueId: "ID1450",
          dnaName: "LP9D_BRECHA_INSULINA_VSL_H04_ID1450",
          linkedCreativeId: "FB-101",
          createdAt: "11:20",
          active: true,
        },
        {
          id: "DNA-1402",
          product: "LP9D",
          bigIdea: "CODIGO",
          mechanism: "JUROS",
          format: "UGC",
          hookVariation: "H02",
          uniqueId: "ID1402",
          dnaName: "LP9D_CODIGO_JUROS_UGC_H02_ID1402",
          linkedCreativeId: "GG-211",
          createdAt: "11:28",
          active: true,
        },
        {
          id: "DNA-1076",
          product: "LP9D",
          bigIdea: "SEGREDO",
          mechanism: "SOL",
          format: "REELS",
          hookVariation: "H01",
          uniqueId: "ID1076",
          dnaName: "LP9D_SEGREDO_SOL_REELS_H01_ID1076",
          linkedCreativeId: "TT-077",
          createdAt: "11:35",
          active: true,
        },
      ],
      scriptEditor:
        "[00:00-00:20] LEAD: Dor central do avatar\n[00:20-02:10] BODY: Mecanismo unico + prova\n[02:10-03:00] OFFER: CTA com urgencia e bonus",
    },
    multiTenant: {
      squads: [
        {
          id: "copy",
          name: "Copy Subsidiaria",
          head: "Head Copy - Ana",
          cost: 182_000,
          revenue: 692_000,
          profit: 510_000,
          marginPct: 73.7,
          efficiencyScore: 91.2,
        },
        {
          id: "media",
          name: "Midia Subsidiaria",
          head: "Head Midia - Caio",
          cost: 1_220_000,
          revenue: 3_980_000,
          profit: 2_760_000,
          marginPct: 69.4,
          efficiencyScore: 88.4,
        },
        {
          id: "tech",
          name: "Tech/CRO Subsidiaria",
          head: "Head Tech - Bruno",
          cost: 148_000,
          revenue: 525_000,
          profit: 377_000,
          marginPct: 71.8,
          efficiencyScore: 86.9,
        },
      ],
      bestSquadId: "copy",
      lastCalculatedAt: "12:04",
    },
    trafficAttribution: {
      squads: {
        meta: { targetCpa: 140, currentCpa: 148, roas: 2.58, stability48h: 78 },
        google: { targetCpa: 150, currentCpa: 141, roas: 2.71, stability48h: 84 },
        native: { targetCpa: 130, currentCpa: 136, roas: 2.22, stability48h: 67 },
      },
      deepAttribution: [
        { creativeId: "FB-101", source: "meta", netProfit: 284_000, ltv: 1_980 },
        { creativeId: "GG-211", source: "google", netProfit: 319_000, ltv: 2_360 },
        { creativeId: "TT-077", source: "native", netProfit: 177_000, ltv: 1_860 },
      ],
      scaleCalculator: {
        suggestedIncreasePct: 15,
        reason: "CPA dentro do intervalo e estabilidade > 75 nas ultimas 48h.",
      },
    },
    editorsProduction: {
      hookLibrary: [
        { hook: "Pare de escalar no escuro", creativeId: "FB-101", hookRate: 31.8 },
        { hook: "Erro silencioso de retencao", creativeId: "TT-077", hookRate: 30.4 },
      ],
      retentionHeatmap: [
        { second: 8, dropOff: 7.5 },
        { second: 17, dropOff: 12.2 },
        { second: 41, dropOff: 18.1 },
      ],
      patternInterruptChecklist: {
        every3s: true,
        soundDesign: true,
        vfx: false,
      },
    },
    techCro: {
      lcpSeconds: 1.18,
      abTests: [
        { test: "Headline LP", variantA: 4.8, variantB: 5.4, winner: "B" },
        { test: "Preco checkout", variantA: 5.6, variantB: 5.1, winner: "A" },
      ],
      checkout: {
        cartAbandonment: 41.2,
        checkoutConversion: 5.8,
        gatewayAlert: false,
      },
      upsellFlow: [
        { step: "Order Bump", clickRate: 26.1 },
        { step: "Upsell 1", clickRate: 17.8 },
        { step: "Upsell 2", clickRate: 9.6 },
      ],
    },
  },
  customerCentrality: {
    leads: [
      {
        leadId: "LEAD-FB101-0001",
        awarenessStage: "product_aware",
        lastVslId: "FB-101",
        watchSeconds: 138,
        watchCompletionPct: 62.4,
        openedEmails7d: 4,
        clickedEmails7d: 2,
        purchases: 1,
        currentLtv: 912,
        predictedLtv90d: 1984,
        lastTouchAt: "2026-03-20T11:58:00.000Z",
      },
      {
        leadId: "LEAD-GG211-0002",
        awarenessStage: "most_aware",
        lastVslId: "GG-211",
        watchSeconds: 164,
        watchCompletionPct: 74.5,
        openedEmails7d: 5,
        clickedEmails7d: 3,
        purchases: 2,
        currentLtv: 1280,
        predictedLtv90d: 2640,
        lastTouchAt: "2026-03-20T12:02:00.000Z",
      },
      {
        leadId: "LEAD-TT077-0003",
        awarenessStage: "problem_aware",
        lastVslId: "TT-077",
        watchSeconds: 78,
        watchCompletionPct: 28.7,
        openedEmails7d: 2,
        clickedEmails7d: 0,
        purchases: 0,
        currentLtv: 320,
        predictedLtv90d: 740,
        lastTouchAt: "2026-03-20T11:41:00.000Z",
      },
    ],
    awarenessDistribution: [
      { stage: "unaware", leads: 0, avgPredictedLtv90d: 0 },
      { stage: "problem_aware", leads: 1, avgPredictedLtv90d: 740 },
      { stage: "solution_aware", leads: 0, avgPredictedLtv90d: 0 },
      { stage: "product_aware", leads: 1, avgPredictedLtv90d: 1984 },
      { stage: "most_aware", leads: 1, avgPredictedLtv90d: 2640 },
    ],
  },
  activityLog: [
    {
      id: "LOG-001",
      actorRole: "Media Buyer",
      actorName: "Gestor Caio",
      action: "pausou criativo",
      entity: "FB-118",
      reason: "baixo Hook Rate",
      timestamp: "11:42",
    },
    {
      id: "LOG-002",
      actorRole: "Copywriter",
      actorName: "Ana",
      action: "subiu versao",
      entity: "V4 - Dor aguda + prova",
      reason: "iteracao para elevar Hold Rate",
      timestamp: "11:48",
    },
    {
      id: "LOG-003",
      actorRole: "Editor",
      actorName: "Nati",
      action: "publicou corte",
      entity: "YT-034 V3",
      reason: "feedback de retencao do gestor",
      timestamp: "11:53",
    },
  ],
};
