import type { WarRoomData } from "./types";

export const mockWarRoomData: WarRoomData = {
  source: "mock",
  sourceLabel: "Mock local",
  updatedAt: new Date().toISOString(),
  globalOverview: {
    investment: 1_920_000,
    revenue: 5_580_000,
    utmifySyncAt: "Agora mesmo",
    trafficSources: [
      { source: "Facebook Ads", spend: 980_000 },
      { source: "Google/YouTube", spend: 620_000 },
      { source: "TikTok Ads", spend: 210_000 },
      { source: "Native + Afiliados", spend: 110_000 },
    ],
  },
  squads: {
    facebook: {
      name: "Squad Facebook",
      focus: "FB Ads + UGC",
      creativeVelocity: 17,
      creativeVelocityTarget: 14,
      validatedCreatives: 11,
      managerComment:
        "CPM estabilizou, mas 3 criativos perderam tracao no dia 2. Prioridade: novas aberturas nos primeiros 5 segundos.",
    },
    googleYoutube: {
      name: "Squad Google/YouTube",
      focus: "Search + VVC + Display",
      creativeVelocity: 9,
      creativeVelocityTarget: 12,
      validatedCreatives: 5,
      managerComment:
        "Search performando com CAC baixo. Gargalo na camada de VVC com baixo hold rate apos 15s.",
    },
    tiktok: {
      name: "Squad TikTok",
      focus: "UGC velocity + Spark Ads",
      creativeVelocity: 14,
      creativeVelocityTarget: 16,
      validatedCreatives: 7,
      managerComment: "Squad com bom volume, mas com sinais iniciais de fadiga por frequencia em criativos campeoes.",
    },
  },
  liveAdsTracking: [
    {
      id: "FB-101",
      squad: "facebook",
      campaign: "Scale UGC CBO",
      adName: "Dor aguda + prova social",
      impressions: 182_440,
      clicks: 13_830,
      views3s: 63_671,
      views15s: 21_200,
      ic: 3_102,
      lp: 9_741,
      roas: 2.7,
      frequency: 2.6,
      uniqueCtr: 2.9,
      aov: 347,
      upsellConversion: 18.4,
      ltv: 1_980,
      cpa: 124,
      trend24h: {
        hookRate: [30.8, 31.2, 31.6, 32.1, 31.8, 31.4, 31.0, 31.8],
        holdRate: [33.5, 34.2, 34.9, 34.5, 34.1, 33.8, 33.4, 33.3],
        roas: [2.3, 2.4, 2.5, 2.7, 2.8, 2.8, 2.7, 2.7],
      },
      frequencyTrend3d: [2.2, 2.4, 2.6],
      uniqueCtrTrend3d: [3.1, 3.0, 2.9],
    },
    {
      id: "FB-118",
      squad: "facebook",
      campaign: "Retargeting D7",
      adName: "Quebra de objecao de preco",
      impressions: 96_200,
      clicks: 5_940,
      views3s: 25_012,
      views15s: 4_430,
      ic: 890,
      lp: 3_460,
      roas: 1.9,
      frequency: 3.9,
      uniqueCtr: 1.1,
      aov: 286,
      upsellConversion: 9.2,
      ltv: 1_280,
      cpa: 192,
      trend24h: {
        hookRate: [21.5, 20.8, 19.9, 19.5, 18.9, 18.5, 18.2, 17.9],
        holdRate: [23.1, 22.4, 21.2, 20.4, 19.5, 18.7, 18.0, 17.7],
        roas: [2.2, 2.1, 2.0, 2.0, 1.9, 1.9, 1.9, 1.9],
      },
      frequencyTrend3d: [3.2, 3.5, 3.9],
      uniqueCtrTrend3d: [1.5, 1.3, 1.1],
    },
    {
      id: "YT-034",
      squad: "googleYoutube",
      campaign: "YouTube VVC Broad",
      adName: "Comparativo visual 45s",
      impressions: 130_900,
      clicks: 8_550,
      views3s: 32_070,
      views15s: 5_904,
      ic: 1_204,
      lp: 6_020,
      roas: 2.1,
      frequency: 2.1,
      uniqueCtr: 1.8,
      aov: 318,
      upsellConversion: 14.9,
      ltv: 1_720,
      cpa: 161,
      trend24h: {
        hookRate: [25.3, 25.8, 25.0, 24.9, 24.7, 24.6, 24.5, 24.5],
        holdRate: [20.9, 20.4, 19.8, 19.6, 19.4, 19.2, 18.9, 18.4],
        roas: [2.3, 2.2, 2.2, 2.2, 2.1, 2.1, 2.1, 2.1],
      },
      frequencyTrend3d: [1.8, 1.9, 2.1],
      uniqueCtrTrend3d: [2.1, 1.9, 1.8],
    },
    {
      id: "GG-211",
      squad: "googleYoutube",
      campaign: "Search High Intent",
      adName: "Headline DR direcional",
      impressions: 74_330,
      clicks: 7_210,
      views3s: 26_313,
      views15s: 13_945,
      ic: 1_833,
      lp: 5_892,
      roas: 3.2,
      frequency: 1.7,
      uniqueCtr: 3.7,
      aov: 401,
      upsellConversion: 22.3,
      ltv: 2_360,
      cpa: 138,
      trend24h: {
        hookRate: [33.2, 34.0, 34.5, 35.0, 35.4, 35.1, 35.0, 35.4],
        holdRate: [49.5, 50.4, 51.0, 51.9, 52.5, 52.1, 51.8, 53.0],
        roas: [2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.1, 3.2],
      },
      frequencyTrend3d: [1.5, 1.6, 1.7],
      uniqueCtrTrend3d: [3.9, 3.8, 3.7],
    },
    {
      id: "TT-077",
      squad: "tiktok",
      campaign: "Spark Scale 25-44",
      adName: "POV transformacao em 18s",
      impressions: 214_110,
      clicks: 12_820,
      views3s: 69_900,
      views15s: 16_420,
      ic: 1_940,
      lp: 8_880,
      roas: 2.4,
      frequency: 3.8,
      uniqueCtr: 1.2,
      aov: 336,
      upsellConversion: 16.1,
      ltv: 1_860,
      cpa: 172,
      trend24h: {
        hookRate: [34.2, 33.7, 33.1, 32.9, 32.7, 32.3, 32.0, 31.6],
        holdRate: [26.2, 25.8, 25.2, 24.8, 24.2, 23.7, 23.1, 22.6],
        roas: [2.8, 2.7, 2.7, 2.6, 2.6, 2.5, 2.5, 2.4],
      },
      frequencyTrend3d: [3.0, 3.4, 3.8],
      uniqueCtrTrend3d: [1.8, 1.5, 1.2],
    },
  ],
  creativeFactory: {
    tasks: [
      {
        id: "TASK-001",
        squad: "facebook",
        title: "V3 - Hook anti-erro de escalada",
        owner: "Copy Ana",
        status: "Roteiro",
        metricContext: "Hold < 20% em FB-118",
        updatedAt: "09:40",
      },
      {
        id: "TASK-002",
        squad: "facebook",
        title: "UGC autoridade com prova visual",
        owner: "Creator Leo",
        status: "Gravacao",
        metricContext: "Hook em queda nas ultimas 24h",
        updatedAt: "10:15",
      },
      {
        id: "TASK-003",
        squad: "googleYoutube",
        title: "Cut 30s para VVC broad",
        owner: "Editor Nati",
        status: "Edicao",
        metricContext: "Retencao baixa apos 15s",
        updatedAt: "10:33",
      },
      {
        id: "TASK-004",
        squad: "googleYoutube",
        title: "Search variant CTA final",
        owner: "Copy Bruno",
        status: "Teste",
        metricContext: "Escalar CTR sem subir CPC",
        updatedAt: "11:02",
      },
      {
        id: "TASK-005",
        squad: "facebook",
        title: "Winner UGC depoimento selfie",
        owner: "Squad FB",
        status: "Winner",
        metricContext: "ROAS > 2.5 em 48h",
        updatedAt: "11:29",
      },
      {
        id: "TASK-006",
        squad: "tiktok",
        title: "Pattern Interrupt para Spark V2",
        owner: "Editor Nati",
        status: "Teste",
        metricContext: "Fadiga detectada em TT-077",
        updatedAt: "11:38",
      },
    ],
  },
  dailyBriefing: [
    {
      id: "BRIEF-1",
      squad: "facebook",
      trafficManagerComment:
        "Criativo FB-118 caiu para Hold 17,7%. Preciso de V2 com transicao de prova antes dos 12s e CTA aberto.",
      replies: [
        {
          role: "Copy",
          author: "Ana",
          version: "V2",
          assetUrl: "https://drive.google.com/file/d/brief-fb-v2",
          note: "Abri com pergunta direta e antecipei mecanismo no segundo 8.",
        },
        {
          role: "Edicao",
          author: "Nati",
          version: "V3",
          assetUrl: "https://drive.google.com/file/d/brief-fb-v3",
          note: "Nova trilha, corte mais rapido e CTA final em tela cheia.",
        },
      ],
    },
    {
      id: "BRIEF-2",
      squad: "googleYoutube",
      trafficManagerComment:
        "VVC com Hook 24,5%. Preciso teste de mini-historia com prova visual ate 15s para destravar retencao.",
      replies: [
        {
          role: "Copy",
          author: "Bruno",
          version: "V2",
          assetUrl: "https://drive.google.com/file/d/brief-yt-v2",
          note: "Roteiro com ponte narrativa e promessa mais explicita no inicio.",
        },
      ],
    },
    {
      id: "BRIEF-3",
      squad: "tiktok",
      trafficManagerComment:
        "Criativo TT-077 com sinais de fadiga. Preciso V2 com pattern interrupt nos 2 primeiros segundos.",
      replies: [
        {
          role: "Edicao",
          author: "Nati",
          version: "V2",
          assetUrl: "https://drive.google.com/file/d/brief-tt-v2",
          note: "Inserido corte de surpresa no frame inicial para recuperar CTR unico.",
        },
      ],
    },
  ],
  finance: {
    netRevenue: 2_120_000,
    profitMargin: 38.0,
    contributionMargin: 31.5,
    approvalRate: 87.2,
    approvalCard: 84.3,
    approvalPix: 93.1,
    ltv24h: 512,
    upsellTakeRate: 21.4,
    ltv: 1_930,
  },
  contingency: {
    domains: [
      { name: "checkout-principal.com", status: "ok", score: 92, lastCheck: "12:03" },
      { name: "reserva-warroom.com", status: "warning", score: 68, lastCheck: "12:03" },
    ],
    adAccounts: [
      { name: "BM Escala Latam", status: "ok", score: 88, lastCheck: "12:02" },
      { name: "Google Ads Conta 02", status: "blocked", score: 34, lastCheck: "12:04" },
    ],
    fanpages: [
      { name: "Pagina Oficial DR", status: "ok", score: 90, lastCheck: "12:05" },
      { name: "Pagina Escala 02", status: "warning", score: 61, lastCheck: "12:05" },
    ],
  },
  enterprise: {
    ceoFinance: {
      grossRevenue: 5_580_000,
      adSpend: 1_920_000,
      gatewayFees: 201_000,
      nfseTaxes: 474_000,
      netProfit: 2_985_000,
      mer: 2.91,
      ltvCohorts: {
        d30: 920,
        d60: 1_480,
        d90: 1_930,
      },
      paybackDays: 17,
      taxProvision: 474_000,
    },
    copyResearch: {
      uniqueMechanismProblem: "Saturacao criativa acelera CAC quando o avatar para de se reconhecer no angulo.",
      uniqueMechanismSolution: "Sistema de rotacao orientado por Pattern Interrupt + backlog de mecanismos testados por squad.",
      bigIdeaVault: [
        { id: "BIG-1", title: "Metodo anti-escalada cega", saturation: 42, expiresAt: "2026-05-20" },
        { id: "BIG-2", title: "Framework de lucratividade por cohort", saturation: 65, expiresAt: "2026-04-12" },
      ],
      avatarDossier: [
        {
          pain: "Escalar sem previsibilidade de lucro",
          desire: "ROAS estavel com caixa positivo",
          objection: "Ja testei varias copys sem resultado",
          supportInsight: "Ticket tende a subir quando oferta tem comparativo visual direto.",
        },
      ],
      scriptEditor:
        "[00:00-00:20] LEAD: Dor central do avatar\n[00:20-02:10] BODY: Mecanismo unico + prova\n[02:10-03:00] OFFER: CTA com urgencia e bonus",
    },
    trafficAttribution: {
      squads: {
        meta: { targetCpa: 140, currentCpa: 148, roas: 2.58, stability48h: 78 },
        google: { targetCpa: 150, currentCpa: 141, roas: 2.71, stability48h: 84 },
        native: { targetCpa: 130, currentCpa: 136, roas: 2.22, stability48h: 67 },
      },
      deepAttribution: [
        { creativeId: "FB-101", source: "meta", netProfit: 284_000, ltv: 1_980 },
        { creativeId: "GG-211", source: "google", netProfit: 319_000, ltv: 2_360 },
        { creativeId: "TT-077", source: "native", netProfit: 177_000, ltv: 1_860 },
      ],
      scaleCalculator: {
        suggestedIncreasePct: 15,
        reason: "CPA dentro do intervalo e estabilidade > 75 nas ultimas 48h.",
      },
    },
    editorsProduction: {
      hookLibrary: [
        { hook: "Pare de escalar no escuro", creativeId: "FB-101", hookRate: 31.8 },
        { hook: "Erro silencioso de retencao", creativeId: "TT-077", hookRate: 30.4 },
      ],
      retentionHeatmap: [
        { second: 8, dropOff: 7.5 },
        { second: 17, dropOff: 12.2 },
        { second: 41, dropOff: 18.1 },
      ],
      patternInterruptChecklist: {
        every3s: true,
        soundDesign: true,
        vfx: false,
      },
    },
    techCro: {
      lcpSeconds: 1.18,
      abTests: [
        { test: "Headline LP", variantA: 4.8, variantB: 5.4, winner: "B" },
        { test: "Preco checkout", variantA: 5.6, variantB: 5.1, winner: "A" },
      ],
      checkout: {
        cartAbandonment: 41.2,
        checkoutConversion: 5.8,
        gatewayAlert: false,
      },
      upsellFlow: [
        { step: "Order Bump", clickRate: 26.1 },
        { step: "Upsell 1", clickRate: 17.8 },
        { step: "Upsell 2", clickRate: 9.6 },
      ],
    },
  },
  activityLog: [
    {
      id: "LOG-001",
      actorRole: "Media Buyer",
      actorName: "Gestor Caio",
      action: "pausou criativo",
      entity: "FB-118",
      reason: "baixo Hook Rate",
      timestamp: "11:42",
    },
    {
      id: "LOG-002",
      actorRole: "Copywriter",
      actorName: "Ana",
      action: "subiu versao",
      entity: "V4 - Dor aguda + prova",
      reason: "iteracao para elevar Hold Rate",
      timestamp: "11:48",
    },
    {
      id: "LOG-003",
      actorRole: "Editor",
      actorName: "Nati",
      action: "publicou corte",
      entity: "YT-034 V3",
      reason: "feedback de retencao do gestor",
      timestamp: "11:53",
    },
  ],
};
